# Generated by Django 5.0.1 on 2026-04-14 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userplan',
            options={'ordering': ('-joined_at',)},
        ),
        migrations.AlterModelOptions(
            name='usertask',
            options={'ordering': ('-completed_at',)},
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='reward',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='tasks/%Y/%m', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'webm', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
