# Generated by Django 6.0.4 on 2026-04-14 11:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userplan_options_alter_usertask_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='reward',
        ),
        migrations.AddField(
            model_name='plan',
            name='daily_earning_limit',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Maximum daily earning limit', max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_tasks_per_day',
            field=models.PositiveIntegerField(default=20, help_text='Maximum tasks per day'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('silver', 'Silver Plan'), ('gold', 'Gold Plan')], default='basic', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='reward_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Task reward multiplier', max_digits=5),
        ),
        migrations.AddField(
            model_name='task',
            name='ad_url',
            field=models.URLField(blank=True, help_text='Advertisement URL'),
        ),
        migrations.AddField(
            model_name='task',
            name='base_reward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base reward before plan multiplier', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='task',
            name='premium_only',
            field=models.BooleanField(default=False, help_text='Only available to premium plan users'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_duration',
            field=models.PositiveIntegerField(default=30, help_text='Required duration in seconds'),
        ),
        migrations.AddField(
            model_name='task',
            name='survey_data',
            field=models.JSONField(blank=True, default=dict, help_text='Survey questions and options'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('advertise', 'Advertisement'), ('survey', 'Survey'), ('study', 'Study/Education')], default='advertise', max_length=15),
        ),
        migrations.AddField(
            model_name='usertask',
            name='duration_spent',
            field=models.PositiveIntegerField(default=0, help_text='Time spent in seconds'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='reward_earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual reward earned after multiplier', max_digits=10),
        ),
        migrations.AddField(
            model_name='usertask',
            name='survey_answers',
            field=models.JSONField(blank=True, default=dict, help_text='Survey responses'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='verified',
            field=models.BooleanField(default=False, help_text='Whether completion was verified'),
        ),
        migrations.CreateModel(
            name='UserDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('earnings_today', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('user', 'date')},
            },
        ),
    ]
