# Generated by Django 6.0.4 on 2026-04-14 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_plan_reward_plan_daily_earning_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['plan_level']},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ad_url',
        ),
        migrations.RemoveField(
            model_name='task',
            name='base_reward',
        ),
        migrations.RemoveField(
            model_name='task',
            name='premium_only',
        ),
        migrations.RemoveField(
            model_name='task',
            name='required_duration',
        ),
        migrations.RemoveField(
            model_name='task',
            name='survey_data',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='duration_spent',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='reward_earned',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='survey_answers',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='verified',
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Plan 1'), (2, 'Plan 2'), (3, 'Plan 3'), (4, 'Plan 4')], help_text='Plan level (1-4) with fixed amounts', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Required deposit amount to activate this plan', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Plan duration in days'),
        ),
        migrations.DeleteModel(
            name='UserDailyStats',
        ),
    ]
