# Generated by Django 5.0.1 on 2026-04-16 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_task_options_task_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required deposit amount to activate this plan', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='daily_earning_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, help_text='Maximum daily earning limit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_tasks_per_day',
            field=models.PositiveIntegerField(blank=True, default=20, help_text='Maximum tasks per day', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='reward_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Task reward multiplier', max_digits=5, null=True),
        ),
    ]
