# Generated by Django 6.0.4 on 2026-04-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_plan_amount_alter_plan_daily_earning_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_link', models.URLField(blank=True, help_text='Telegram group/channel link', null=True)),
                ('whatsapp_link', models.URLField(blank=True, help_text='WhatsApp group link', null=True)),
                ('support_email', models.EmailField(blank=True, help_text='Support email address', max_length=254, null=True)),
                ('facebook_link', models.URLField(blank=True, help_text='Facebook page link', null=True)),
                ('instagram_link', models.URLField(blank=True, help_text='Instagram profile link', null=True)),
                ('announcement_banner', models.TextField(blank=True, help_text='Announcement banner text', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
