version: '3.9'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: gunicorn novaprofit.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4 --threads 4 --timeout 120 --access-logfile - --error-logfile -

  celery:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: celery -A novaprofit worker -l info --concurrency=3

  celery-beat:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: celery -A novaprofit beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: novaprofit
      POSTGRES_USER: novaprofit
      POSTGRES_PASSWORD: strong_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
