# Generated by Django 5.0.1 on 2026-04-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_plan_options_remove_plan_plan_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Task duration in minutes'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='media',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
