# Generated by Django 6.0.5 on 2026-05-29 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_task_daily_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['user', 'plan'], name='core_userpl_user_id_5ca6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='usertask',
            index=models.Index(fields=['user', 'completed_date'], name='core_userta_user_id_083c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='usertask',
            index=models.Index(fields=['task', 'completed_date'], name='core_userta_task_id_a03fde_idx'),
        ),
    ]
