# Generated by Django 6.0.5 on 2026-05-31 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userplan_core_userpl_user_id_5ca6ef_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Plan expiration date', null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['user', 'is_active'], name='core_userpl_user_id_446756_idx'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['user', 'expires_at'], name='core_userpl_user_id_0f0f28_idx'),
        ),
    ]
