# Generated by Django 6.0.4 on 2026-04-14 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_deposit_options_alter_transaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='reference_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='reference_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TASK', 'Task Reward'), ('ACTIVITY', 'Activity Reward'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('ADJUSTMENT', 'Adjustment')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['user'], name='wallet_depo_user_id_0c0ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['status'], name='wallet_depo_status_931183_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['-requested_at'], name='wallet_depo_request_60305d_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['user', 'status'], name='wallet_depo_user_id_426dda_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='wallet_tran_user_id_b00b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='wallet_tran_status_a49b73_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='wallet_tran_transac_7debff_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='wallet_tran_created_0b36a1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='wallet_tran_user_id_9b1f68_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='wallet_tran_user_id_842d51_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user'], name='wallet_with_user_id_ffb87a_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status'], name='wallet_with_status_e9e494_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['-requested_at'], name='wallet_with_request_1926f1_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', 'status'], name='wallet_with_user_id_63a0c2_idx'),
        ),
    ]
