# Generated by Django 5.0.1 on 2026-04-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_deposit_description_deposit_reference_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deposit',
            name='wallet_depo_user_id_0c0ff9_idx',
        ),
        migrations.RemoveIndex(
            model_name='deposit',
            name='wallet_depo_status_931183_idx',
        ),
        migrations.RemoveIndex(
            model_name='deposit',
            name='wallet_depo_request_60305d_idx',
        ),
        migrations.RemoveIndex(
            model_name='deposit',
            name='wallet_depo_user_id_426dda_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='wallet_tran_user_id_b00b9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='wallet_tran_status_a49b73_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='wallet_tran_transac_7debff_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='wallet_tran_created_0b36a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='wallet_tran_user_id_9b1f68_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='wallet_tran_user_id_842d51_idx',
        ),
        migrations.RemoveIndex(
            model_name='withdrawal',
            name='wallet_with_user_id_ffb87a_idx',
        ),
        migrations.RemoveIndex(
            model_name='withdrawal',
            name='wallet_with_status_e9e494_idx',
        ),
        migrations.RemoveIndex(
            model_name='withdrawal',
            name='wallet_with_request_1926f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='withdrawal',
            name='wallet_with_user_id_63a0c2_idx',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='reference_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('TASK_REWARD', 'Task Reward'), ('ACTIVITY_REWARD', 'Activity Reward'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('ADJUSTMENT', 'Adjustment')], max_length=20),
        ),
    ]
