# Generated by Django 6.0.4 on 2026-04-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_paymentmethod_cryptodeposit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
