# Generated by Django 5.0.1 on 2026-04-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_current_plan_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_plan_level',
        ),
    ]
