# Generated by Django 6.0.5 on 2026-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_plan_level',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Current plan level (0=None, 1-4)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'is_verified', 'created_at'], name='accounts_ot_user_id_868aa9_idx'),
        ),
    ]
