# Generated by Django 6.0.5 on 2026-05-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_delete_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
