# Generated by Django 6.0.5 on 2026-05-29 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_withdrawal_wallet_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cryptodeposit',
            index=models.Index(fields=['user', 'status', 'created_at'], name='wallet_cryp_user_id_a8b2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='wallet_tran_user_id_4e9914_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='wallet_tran_transac_7debff_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', 'status', 'requested_at'], name='wallet_with_user_id_42e462_idx'),
        ),
    ]
