# Generated by Django 6.0.5 on 2026-05-31 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='ad_url',
            field=models.URLField(blank=True, help_text='Link to external ad or website', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='media',
            field=models.ImageField(blank=True, help_text='Image or thumbnail', null=True, upload_to='task_media/'),
        ),
        migrations.AddField(
            model_name='task',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('link', 'External Link')], max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='premium_only',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minimum plan level (0=all, 1-4=plan level)'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_duration',
            field=models.PositiveIntegerField(default=0, help_text='Required seconds to spend on task (0 = no minimum)'),
        ),
        migrations.AddField(
            model_name='task',
            name='survey_data',
            field=models.JSONField(blank=True, default=dict, help_text='Survey questions and options'),
        ),
        migrations.AddField(
            model_name='usertasksubmission',
            name='link_opened_at',
            field=models.DateTimeField(blank=True, help_text='When user opened the external link', null=True),
        ),
        migrations.AddField(
            model_name='usertasksubmission',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Seconds spent on task'),
        ),
        migrations.AddField(
            model_name='usertasksubmission',
            name='timer_completed_at',
            field=models.DateTimeField(blank=True, help_text='When user completed the timer', null=True),
        ),
        migrations.AddField(
            model_name='usertasksubmission',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, help_text='When user started the timer', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('upload', 'Upload'), ('review', 'Review'), ('video', 'Video'), ('ad_link', 'Ad Link'), ('image_review', 'Image Review')], default='quiz', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type', 'is_active'], name='tasks_task_task_ty_1e5b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_active'], name='tasks_task_is_acti_16b97a_idx'),
        ),
        migrations.AddIndex(
            model_name='usertasksubmission',
            index=models.Index(fields=['user', 'task'], name='tasks_usert_user_id_65d9e1_idx'),
        ),
        migrations.AddIndex(
            model_name='usertasksubmission',
            index=models.Index(fields=['status'], name='tasks_usert_status_3d191d_idx'),
        ),
        migrations.AddIndex(
            model_name='usertasksubmission',
            index=models.Index(fields=['user', 'status'], name='tasks_usert_user_id_18a147_idx'),
        ),
    ]
