# Generated by Django 6.0.4 on 2026-04-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_plan_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Current activated plan level (1-4)', null=True),
        ),
    ]
