# Generated by Django 5.0.1 on 2026-04-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_current_plan_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_plan_level',
            field=models.PositiveSmallIntegerField(default=0, help_text='Current plan level (0=None, 1-4)'),
        ),
    ]
